INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('1','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('2','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('3','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('4','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('5','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('6','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('7','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('8','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('9','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('10','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('11','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('12','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('13','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('14','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('15','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('16','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('17','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('18','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('19','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('20','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('21','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('22','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('23','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('24','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('25','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('26','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('27','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('28','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('29','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('30','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('31','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('32','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('33','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('34','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('35','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('36','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('37','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('38','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('39','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('40','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('41','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('42','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('43','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('44','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('45','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('46','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('47','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('48','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('49','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('50','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('51','1',CURRENT_DATE,CURRENT_TIME,'1.2','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('52','1',CURRENT_DATE,CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('53','1',CURRENT_DATE,CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('54','1',CURRENT_DATE,CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('55','1',CURRENT_DATE,CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('56','1',CURRENT_DATE,CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('57','1',CURRENT_DATE,CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('58','1',CURRENT_DATE,CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('59','1',CURRENT_DATE,CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('60','1',CURRENT_DATE,CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('61','1',CURRENT_DATE,CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('1','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('2','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('3','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('4','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('5','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('6','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('7','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('8','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('9','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('10','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('11','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('12','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('13','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('14','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('15','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('16','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('17','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('18','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('19','1','2015-10-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('20','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('21','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('22','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('23','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('24','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('25','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('26','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('27','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('28','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('29','1','2015-10-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('30','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('31','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('32','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('33','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('34','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('35','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('36','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('37','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('38','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('39','1','2015-10-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('40','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('41','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('42','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('43','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('44','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('45','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('46','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('47','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('48','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('49','1','2015-10-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('50','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('51','1','2015-10-07',CURRENT_TIME,'3.2','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('52','1','2015-10-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('53','1','2015-10-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('54','1','2015-10-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('55','1','2015-10-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('56','1','2015-10-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('57','1','2015-10-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('58','1','2015-10-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('59','1','2015-10-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('60','1','2015-10-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('61','1','2015-10-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('1','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('2','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('3','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('4','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('5','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('6','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('7','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('8','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('9','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('10','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('11','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('12','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('13','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('14','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('15','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('16','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('17','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('18','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('19','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('20','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('21','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('22','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('23','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('24','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('25','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('26','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('27','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('28','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('29','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('30','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('31','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('32','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('33','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('34','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('35','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('36','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('37','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('38','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('39','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('40','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('41','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('42','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('43','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('44','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('45','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('46','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('47','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('48','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('49','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('50','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('51','1','2015-11-07',CURRENT_TIME,'5.2','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('52','1','2015-11-07',CURRENT_TIME,'6.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('53','1','2015-11-07',CURRENT_TIME,'7.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('54','1','2015-11-07',CURRENT_TIME,'8.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('55','1','2015-11-07',CURRENT_TIME,'9.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('56','1','2015-11-07',CURRENT_TIME,'10.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('57','1','2015-11-07',CURRENT_TIME,'1.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('58','1','2015-11-07',CURRENT_TIME,'2.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('59','1','2015-11-07',CURRENT_TIME,'3.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('60','1','2015-11-07',CURRENT_TIME,'4.1','0.1','1','1');
INSERT INTO meas_param_sys(ID_SENSORS, STATUS_SENSORS, DATE_MEAS, TIME_MEAS, VALUE_MEAS, RELATIVE_VALUE_MEAS, TRUST_MEAS, WORK_SENSORS)
VALUES ('61','1','2015-11-07',CURRENT_TIME,'5.1','0.1','1','1');