//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.04 at 02:34:45 PM MSK 
//


package ru.rushydro.vniig.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.rushydro.vniig.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.rushydro.vniig.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendSensorValuesResponse }
     * 
     */
    public SendSensorValuesResponse createSendSensorValuesResponse() {
        return new SendSensorValuesResponse();
    }

    /**
     * Create an instance of {@link GetSensorValuesResponse }
     * 
     */
    public GetSensorValuesResponse createGetSensorValuesResponse() {
        return new GetSensorValuesResponse();
    }

    /**
     * Create an instance of {@link SensorInfoValues }
     * 
     */
    public SensorInfoValues createSensorInfoValues() {
        return new SensorInfoValues();
    }

    /**
     * Create an instance of {@link SendCurrentTimeRequest }
     * 
     */
    public SendCurrentTimeRequest createSendCurrentTimeRequest() {
        return new SendCurrentTimeRequest();
    }

    /**
     * Create an instance of {@link SendLevelRequest }
     * 
     */
    public SendLevelRequest createSendLevelRequest() {
        return new SendLevelRequest();
    }

    /**
     * Create an instance of {@link SendSensorValuesRequest }
     * 
     */
    public SendSensorValuesRequest createSendSensorValuesRequest() {
        return new SendSensorValuesRequest();
    }

    /**
     * Create an instance of {@link SensorValues }
     * 
     */
    public SensorValues createSensorValues() {
        return new SensorValues();
    }

    /**
     * Create an instance of {@link SendLevelResponse }
     * 
     */
    public SendLevelResponse createSendLevelResponse() {
        return new SendLevelResponse();
    }

    /**
     * Create an instance of {@link GetSensorValuesRequest }
     * 
     */
    public GetSensorValuesRequest createGetSensorValuesRequest() {
        return new GetSensorValuesRequest();
    }

    /**
     * Create an instance of {@link SendCurrentTimeResponse }
     * 
     */
    public SendCurrentTimeResponse createSendCurrentTimeResponse() {
        return new SendCurrentTimeResponse();
    }

    /**
     * Create an instance of {@link SensorInfoValue }
     * 
     */
    public SensorInfoValue createSensorInfoValue() {
        return new SensorInfoValue();
    }

    /**
     * Create an instance of {@link SensorValue }
     * 
     */
    public SensorValue createSensorValue() {
        return new SensorValue();
    }

}
